config/routes.rb
Candor::Application.routes.draw do
  devise_for :users

  resources :interview_session_schedules

  resources :interview_sessions

  resources :employees

  match 'dashboard' => 'dashboard#index', :as => :dashboard
  resources :interview
  resources :positions
  resources :candidates

  root :to => "dashboard#index"

end

app/models/interview_session_schedule.rb
class InterviewSessionSchedule < ActiveRecord::Base
  belongs_to :employee, :class_name => "Employee", :foreign_key => "employee_id"
  belongs_to :interview_session, :class_name => "InterviewSession", :foreign_key => "interview_session_id"
end

app/controllers/interview_session_schedules_controller.rb
class InterviewSessionSchedulesController < ApplicationController
  # GET /interview_session_schedules
  # GET /interview_session_schedules.xml
  def index
    @interview_session_schedules = InterviewSessionSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @interview_session_schedules }
    end
  end

  # GET /interview_session_schedules/1
  # GET /interview_session_schedules/1.xml
  def show
    @interview_session_schedule = InterviewSessionSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @interview_session_schedule }
    end
  end

  # GET /interview_session_schedules/new
  # GET /interview_session_schedules/new.xml
  def new
    @interview_session_schedule = InterviewSessionSchedule.new
    
    @employees = Employee.all
    @interview_sessions = InterviewSession.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @interview_session_schedule }
    end
  end

  # GET /interview_session_schedules/1/edit
  def edit
    @interview_session_schedule = InterviewSessionSchedule.find(params[:id])
  end

  # POST /interview_session_schedules
  # POST /interview_session_schedules.xml
  def create
    @interview_session_schedule = InterviewSessionSchedule.new(params[:interview_session_schedule])

    respond_to do |format|
      if @interview_session_schedule.save
        format.html { redirect_to(@interview_session_schedule, :notice => 'Interview session schedule was successfully created.') }
        format.xml  { render :xml => @interview_session_schedule, :status => :created, :location => @interview_session_schedule }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interview_session_schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interview_session_schedules/1
  # PUT /interview_session_schedules/1.xml
  def update
    @interview_session_schedule = InterviewSessionSchedule.find(params[:id])

    respond_to do |format|
      if @interview_session_schedule.update_attributes(params[:interview_session_schedule])
        format.html { redirect_to(@interview_session_schedule, :notice => 'Interview session schedule was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @interview_session_schedule.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interview_session_schedules/1
  # DELETE /interview_session_schedules/1.xml
  def destroy
    @interview_session_schedule = InterviewSessionSchedule.find(params[:id])
    @interview_session_schedule.destroy

    respond_to do |format|
      format.html { redirect_to(interview_session_schedules_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/interview_session_schedules_helper.rb
module InterviewSessionSchedulesHelper
end

app/views/interview_session_schedules/_form.html.erb
<%= form_for(@interview_session_schedule) do |f| %>
  <% if @interview_session_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interview_session_schedule.errors.count, "error") %> prohibited this interview_session_schedule from being saved:</h2>

      <ul>
      <% @interview_session_schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interview_session_id %><br />
    <%= select ("interview_session_schedule", "interview_session_id", @interview_sessions.map {|u| [u.start_time,u.id]}) %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br />    
    <%= select ("interview_session_schedule", "employee_id", @employees.map {|u| [u.employee_name,u.id]}) %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br />
    <%= f.check_box :accepted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interview_session_schedules/edit.html.erb
<h1>Editing interview_session_schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @interview_session_schedule %> |
<%= link_to 'Back', interview_session_schedules_path %>

app/views/interview_session_schedules/index.html.erb
<h1>Listing interview_session_schedules</h1>

<table>
  <tr>
    <th>Interview session</th>
    <th>Employee</th>
    <th>Accepted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interview_session_schedules.each do |interview_session_schedule| %>
  <tr>
    <td><%= interview_session_schedule.interview_session_id %></td>
    <td><%= interview_session_schedule.employee_id %></td>
    <td><%= interview_session_schedule.accepted %></td>
    <td><%= link_to 'Show', interview_session_schedule %></td>
    <td><%= link_to 'Edit', edit_interview_session_schedule_path(interview_session_schedule) %></td>
    <td><%= link_to 'Destroy', interview_session_schedule, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interview session schedule', new_interview_session_schedule_path %>

app/views/interview_session_schedules/new.html.erb
<h1>New interview_session_schedule</h1>

<%= render 'form' %>

<%= link_to 'Back', interview_session_schedules_path %>

app/views/interview_session_schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Interview session:</b>
  <%= @interview_session_schedule.interview_session_id %>
</p>

<p>
  <b>Employee:</b>
  <%= @interview_session_schedule.employee_id %>
</p>

<p>
  <b>Accepted:</b>
  <%= @interview_session_schedule.accepted %>
</p>


<%= link_to 'Edit', edit_interview_session_schedule_path(@interview_session_schedule) %> |
<%= link_to 'Back', interview_session_schedules_path %>