config/routes.rb
Candor::Application.routes.draw do
  devise_for :users

  resources :interview_session_schedules

  resources :interview_sessions

  resources :employees

  match 'dashboard' => 'dashboard#index', :as => :dashboard
  resources :interview
  resources :positions
  resources :candidates

  root :to => "dashboard#index"

end

app/models/interview_session.rb
class InterviewSession < ActiveRecord::Base
  belongs_to :candidate
  has_many :interview_session_schedules, :class_name => "InterviewSessionSchedule"
  has_many :employees, :through => :interview_session_schedules
end

app/controllers/interview_sessions_controller.rb
class InterviewSessionsController < ApplicationController
  # GET /interview_sessions
  # GET /interview_sessions.xml
  def index
    @interview_sessions = InterviewSession.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @interview_sessions }
    end
  end

  # GET /interview_sessions/1
  # GET /interview_sessions/1.xml
  def show
    @interview_session = InterviewSession.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @interview_session }
    end
  end

  # GET /interview_sessions/new
  # GET /interview_sessions/new.xml
  def new
    @interview_session = InterviewSession.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @interview_session }
    end
  end

  # GET /interview_sessions/1/edit
  def edit
    @interview_session = InterviewSession.find(params[:id])
  end

  # POST /interview_sessions
  # POST /interview_sessions.xml
  def create
    @interview_session = InterviewSession.new(params[:interview_session])

    respond_to do |format|
      if @interview_session.save
        format.html { redirect_to(@interview_session, :notice => 'Interview session was successfully created.') }
        format.xml  { render :xml => @interview_session, :status => :created, :location => @interview_session }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @interview_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /interview_sessions/1
  # PUT /interview_sessions/1.xml
  def update
    @interview_session = InterviewSession.find(params[:id])

    respond_to do |format|
      if @interview_session.update_attributes(params[:interview_session])
        format.html { redirect_to(@interview_session, :notice => 'Interview session was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @interview_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /interview_sessions/1
  # DELETE /interview_sessions/1.xml
  def destroy
    @interview_session = InterviewSession.find(params[:id])
    @interview_session.destroy

    respond_to do |format|
      format.html { redirect_to(interview_sessions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/interview_sessions_helper.rb
module InterviewSessionsHelper
end

app/views/interview_sessions/_form.html.erb
<%= form_for(@interview_session) do |f| %>
  <% if @interview_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interview_session.errors.count, "error") %> prohibited this interview_session from being saved:</h2>

      <ul>
      <% @interview_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.text_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.text_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :panel_type %><br />
    <%= f.text_field :panel_type %>
  </div>
  <div class="field">
    <%= f.label :candidate_id %><br />
    <%= f.text_field :candidate_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interview_sessions/edit.html.erb
<h1>Editing interview_session</h1>

<%= render 'form' %>

<%= link_to 'Show', @interview_session %> |
<%= link_to 'Back', interview_sessions_path %>

app/views/interview_sessions/index.html.erb
<h1>Listing interview_sessions</h1>

<table>
  <tr>
    <th>Start time</th>
    <th>End time</th>
    <th>Location</th>
    <th>Panel type</th>
    <th>Candidate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interview_sessions.each do |interview_session| %>
  <tr>
    <td><%= interview_session.start_time %></td>
    <td><%= interview_session.end_time %></td>
    <td><%= interview_session.location %></td>
    <td><%= interview_session.panel_type %></td>
    <td><%= interview_session.candidate_id %></td>
    <td><%= link_to 'Show', interview_session %></td>
    <td><%= link_to 'Edit', edit_interview_session_path(interview_session) %></td>
    <td><%= link_to 'Destroy', interview_session, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Interview session', new_interview_session_path %>

app/views/interview_sessions/new.html.erb
<h1>New interview_session</h1>

<%= render 'form' %>

<%= link_to 'Back', interview_sessions_path %>

app/views/interview_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start time:</b>
  <%= @interview_session.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @interview_session.end_time %>
</p>

<p>
  <b>Location:</b>
  <%= @interview_session.location %>
</p>

<p>
  <b>Panel type:</b>
  <%= @interview_session.panel_type %>
</p>

<p>
  <b>Candidate:</b>
  <%= @interview_session.candidate.candidate_name%>
</p>


<%= link_to 'Edit', edit_interview_session_path(@interview_session) %> |
<%= link_to 'Back', interview_sessions_path %>